version: '3.9'

services:
    fiber-boilerplate:
        deploy:
            replicas: 1
        image: fiber-production
        build: .
        tty: true
        ports:
            - 3001:3000
        env_file:
            - secret.env