version: '3.9'

services:
    fiber-boilerplate:
        deploy:
            replicas: 1
        build: .
        env_file:
            - ./config.env
        tty: true
        ports:
            - 3001:3000